Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [1]:
import numpy as np

In [3]:
#task1
empty_array = np.empty((2,2))
print(empty_array)

[[4.73135210e-310 0.00000000e+000]
 [6.91444561e-310 6.91444561e-310]]


In [5]:
#task2
ones_array = np.ones((4,2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
#task3
fill_value = np.full((3,4),3)#np.fill(row,column),number value
print(fill_value)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [14]:
#task4
array = np.array([[1,3,4],[2,5,7]])
zeros_array = np.zeros_like(array)
print(zeros_array)

[[0 0 0]
 [0 0 0]]


In [18]:
#task5
array = np.array([[1,6,9,4], [2,4,6,8]])#make array
ones_array = np.ones_like(array)#use np.ones_like to made array
print(ones_array)

[[1 1 1 1]
 [1 1 1 1]]


In [19]:
#task6
new_list = [1,2,3,4]
numpy_array = np.array(new_list)
print(numpy_array)

[1 2 3 4]


4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [23]:
import numpy as np

In [25]:
#task1
array = np.arange(10, 50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [30]:
#task2
matrix = np.arange(0,9)
reshape = matrix.reshape(3,3)
print(reshape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [33]:
#task3
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
#task4
random = np.random.random(30)
mean = array.mean()
print(random)
print(mean)

[0.53667457 0.13084173 0.02660714 0.53515793 0.14263483 0.60995279
 0.88172863 0.86377087 0.3742285  0.67924289 0.72310622 0.04061684
 0.45732639 0.58285561 0.46046611 0.02847862 0.60458027 0.29224015
 0.65797484 0.67370908 0.85231354 0.59400839 0.27571238 0.0462732
 0.40424292 0.18583807 0.05951801 0.86393847 0.00667088 0.61096718]
29.5


In [44]:
#task5
array = np.random.random(10)
minimum = np.min(array)
maximum = np.max(array)
print(array)
print(minimum)
print(maximum)

[0.95975314 0.77283502 0.91830458 0.49484354 0.43272917 0.76547282
 0.75282491 0.10628075 0.78677356 0.25336181]
0.1062807475948564
0.959753136864893


In [48]:
#task6
array = np.zeros(10)
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [58]:
#task7
arr = [1,2,0,0,4,0]
reverse = arr[::-1]
print(reverse)

[0, 4, 0, 0, 2, 1]


In [59]:
#task8
array = np.ones((3,3))
array [1:-1,1:-1] = 0
print(array)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [65]:
#task9
array = np.zeros((8,8))
array [1::2, ::2] = 1
array [::2, 1::2] = 1
print(array)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [67]:
import numpy as np
x = np.array([[1,2], [3,5]])
y = np.array([[5,6], [7,8]])
v = np.array([9,10])
w = np.array([11, 12])

In [68]:
#task1
addition = x+y
print(addition)

[[ 6  8]
 [10 13]]


In [69]:
#task2
subraction = w-v
print(subraction)

[2 2]


In [70]:
#task3
print (2*x)

[[ 2  4]
 [ 6 10]]


In [72]:
#task4
print (x**2)

[[ 1  4]
 [ 9 25]]


In [73]:
#task5
vw = np.dot(v, w)
xv =np.dot(x, v)
xy = np.dot(x, y)

print(vw)
print(xv)
print(xy)

219
[29 77]
[[19 22]
 [50 58]]


In [75]:
#task6
along_row = np.concatenate((x,y), axis =1)
print(along_row)
along_column = np.concatenate ((v[:, np.newaxis], w[:, np.newaxis]), axis =1)
print(along_column)

[[1 2 5 6]
 [3 5 7 8]]
[[ 9 11]
 [10 12]]


In [77]:
#task7
try:
  concatenateXV = np.concatenate((x, v), axis = 1)
  print(concatenateXV)
except Exception as e:
  print(e)

all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [78]:
import numpy as np

In [79]:
a = np.array([[3,4], [7,8]])
b = np.array([[5,3],[2,1]])

In [83]:
#task1
inverse = np.linalg.inv(a)
matrix = np.dot(inverse, a)
print(matrix)

[[1.00000000e+00 0.00000000e+00]
 [5.55111512e-16 1.00000000e+00]]


In [84]:
#task2
ab = np.dot(a,b)
ba = np.dot(b,a)
print(ab)
print(ba)

[[23 13]
 [51 29]]
[[36 44]
 [13 16]]


In [88]:
#task3
abT = np.transpose(np.dot(a,b))
bTaT = np.dot(np.transpose(b), (np.transpose(a)))
print(abT)
print(bTaT)

[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


In [93]:
#solve eqn
a = np.array([[2, -3, 1], [1, -2, 1], [3, 1, -1]])
b = np.array([1, -3, 9])
inverseA = np.linalg.inv(a)
x = np.dot(inverseA, b)
print(x)

[  0.66666667  -3.33333333 -10.33333333]


4.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

————————– The - End ————————-

In [5]:
#task1
import time
import numpy as np

In [6]:
#task1
def add():
 list1 = [i for i in range (1000000)]
 list2 = [i for i in range (1000000)]

 start = time.time()
 result = [list1[i] + list2[i] for i in range(1000000)]
 end = time.time()
 return end - start

def numpy_array_add():
  arr1 = np.arange(1000000)
  arr2 = np.arange(1000000)

  start = time.time()
  result = arr1 + arr2
  end = time.time()
  return end - start

print(add())
print(numpy_array_add())

0.12842702865600586
0.002227306365966797


In [7]:
#task2
def multiply():
 list1 = [i for i in range (1000000)]
 list2 = [i for i in range (1000000)]

 start = time.time()
 result = [list1[i] * list2[i] for i in range(1000000)]
 end = time.time()
 return end - start

def numpy_array_multiply():
  arr1 = np.arange(1000000)
  arr2 = np.arange(1000000)

  start = time.time()
  result = arr1 * arr2
  end = time.time()
  return end - start

print(multiply())
print(numpy_array_multiply())

0.12632417678833008
0.002208709716796875


In [8]:
#task3
def dot():
  list1 = [i for i in range(1000000)]
  list2 = [i for i in range(1000000)]
  start = time.time()
  result = sum(list1[i] * list2[i] for i in range(1000000))
  end = time.time()
  return end - start

def numpy_dot():
  arr1 = np.arange(1000000)
  arr2 = np.arange(1000000)
  start = time.time()
  result = np.dot(arr1, arr2)
  end = time.time()
  return end - start

print(dot())
print(numpy_dot())

0.142897367477417
0.001603841781616211


In [13]:
#task4
def matrix_multiply():
  matrix1 = [[i for i in range(100)] for j in range(100)]
  matrix2 = [[i for i in range(100)] for j in range(100)]
  start = time.time()
  result = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(100)) for j in range (100)] for i in range(100)]
  end = time.time()
  return end - start

def numpy_matrix_multiply():
  matrix1 = np.random.rand(100, 100)
  matrix2 = np.random.rand(100, 100)
  start = time.time()
  result = np.dot(matrix1, matrix2)
  end = time.time()
  return end - start

print(matrix_multiply())
print(numpy_matrix_multiply())

0.15940594673156738
0.00020432472229003906
